package com.tcsh.user.entity;

// Generated 2014-9-8 12:11:19 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserExt generated by hbm2java
 */
@Entity
@Table(name = "user_ext", schema = "public")
public class UserExtEntity implements java.io.Serializable {
	private static final long serialVersionUID = -4455669699710810971L;

	private Integer userId;
	private String realname;
	private String userAvatar;
	private Short gender;
	private Timestamp birthday;
	private String Integerro;
	private String comefrom;
	private String qq;
	private String userSignature;

	public UserExtEntity() {
	}

	public UserExtEntity(Integer userId, short gender) {
		this.userId = userId;
		this.gender = gender;
	}

	public UserExtEntity(Integer userId, String realname, String userAvatar,
			Short gender, Timestamp birthday, String Integerro, String comefrom,
			String qq, String userSignature) {
		this.userId = userId;
		this.realname = realname;
		this.userAvatar = userAvatar;
		this.gender = gender;
		this.birthday = birthday;
		this.Integerro = Integerro;
		this.comefrom = comefrom;
		this.qq = qq;
		this.userSignature = userSignature;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "realname", length = 30)
	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	@Column(name = "user_avatar", length = 100)
	public String getUserAvatar() {
		return this.userAvatar;
	}

	public void setUserAvatar(String userAvatar) {
		this.userAvatar = userAvatar;
	}

	@Column(name = "gender", nullable = false)
	public short getGender() {
		return this.gender;
	}

	public void setGender(Short gender) {
		this.gender = gender;
	}

	@Column(name = "birthday", length = 35)
	public Timestamp getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Timestamp birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Integerro")
	public String getIntegerro() {
		return this.Integerro;
	}

	public void setIntegerro(String Integerro) {
		this.Integerro = Integerro;
	}

	@Column(name = "comefrom", length = 150)
	public String getComefrom() {
		return this.comefrom;
	}

	public void setComefrom(String comefrom) {
		this.comefrom = comefrom;
	}

	@Column(name = "qq", length = 100)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "user_signature")
	public String getUserSignature() {
		return this.userSignature;
	}

	public void setUserSignature(String userSignature) {
		this.userSignature = userSignature;
	}

}
