package com.tcsh.user.entity;

// Generated 2014-9-8 12:11:19 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserBase generated by hbm2java
 * @author sunny
 */
@Entity
@Table(name = "user_base", schema = "public")
public class UserBaseEntity implements java.io.Serializable {
	private static final long serialVersionUID = -2605129418632970171L;
	
	private Integer id;
	private String nickname;
	private String userEmail;
	private String telephone;
	private String userPassword;
	private Timestamp registerTime;
	private String registerIp;
	private Timestamp lastLogIntegerime;		//最后一次登录时间 
	private String lastLoginIp;					//最后一次登录IP
	private Integer loginCount;					//登录次数
	private Timestamp errorTime;
	private Integer errorCount;					//登录错误次数
	private String errorIp;						//登录错误IP
	private Integer rank;						//用户等级
	private Short userState;					//用户当前状态

	public UserBaseEntity() {
	}

	public UserBaseEntity(Integer id, String userEmail, String userPassword,
			Timestamp registerTime, String registerIp, Timestamp lastLogIntegerime,
			String lastLoginIp, Integer loginCount, Integer rank, Short userState) {
		this.id = id;
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.registerTime = registerTime;
		this.registerIp = registerIp;
		this.lastLogIntegerime = lastLogIntegerime;
		this.lastLoginIp = lastLoginIp;
		this.loginCount = loginCount;
		this.rank = rank;
		this.userState = userState;
	}

	public UserBaseEntity(Integer id, String nickname, String userEmail,
			String telephone, String userPassword, Timestamp registerTime,
			String registerIp, Timestamp lastLogIntegerime, String lastLoginIp,
			Integer loginCount, Integer rank, Short userState) {
		this.id = id;
		this.nickname = nickname;
		this.userEmail = userEmail;
		this.telephone = telephone;
		this.userPassword = userPassword;
		this.registerTime = registerTime;
		this.registerIp = registerIp;
		this.lastLogIntegerime = lastLogIntegerime;
		this.lastLoginIp = lastLoginIp;
		this.loginCount = loginCount;
		this.rank = rank;
		this.userState = userState;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nickname", length = 50)
	public String getNickname() {
		return this.nickname;
	}

	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	@Column(name = "user_email", nullable = false, length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "telephone", length = 20)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "user_password", nullable = false, length = 50)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "register_time", nullable = false, length = 35)
	public Timestamp getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Timestamp registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "register_ip", nullable = false, length = 50)
	public String getRegisterIp() {
		return this.registerIp;
	}

	public void setRegisterIp(String registerIp) {
		this.registerIp = registerIp;
	}

	@Column(name = "last_login_time", nullable = false, length = 35)
	public Timestamp getLastLogIntegerime() {
		return this.lastLogIntegerime;
	}

	public void setLastLogIntegerime(Timestamp lastLogIntegerime) {
		this.lastLogIntegerime = lastLogIntegerime;
	}

	@Column(name = "last_login_ip", nullable = false, length = 50)
	public String getLastLoginIp() {
		return this.lastLoginIp;
	}

	public void setLastLoginIp(String lastLoginIp) {
		this.lastLoginIp = lastLoginIp;
	}

	@Column(name = "login_count", nullable = false)
	public Integer getLoginCount() {
		return this.loginCount;
	}

	public void setLoginCount(Integer loginCount) {
		this.loginCount = loginCount;
	}

	@Column(name = "error_time")
	public Timestamp getErrorTime() {
		return errorTime;
	}

	public void setErrorTime(Timestamp errorTime) {
		this.errorTime = errorTime;
	}

	@Column(name = "error_count")
	public Integer getErrorCount() {
		return errorCount;
	}

	public void setErrorCount(Integer errorCount) {
		this.errorCount = errorCount;
	}

	@Column(name = "error_ip")
	public String getErrorIp() {
		return errorIp;
	}

	public void setErrorIp(String errorIp) {
		this.errorIp = errorIp;
	}

	@Column(name = "rank", nullable = false)
	public Integer getRank() {
		return this.rank;
	}

	public void setRank(Integer rank) {
		this.rank = rank;
	}

	@Column(name = "user_state", nullable = false)
	public Short getUserState() {
		return this.userState;
	}

	public void setUserState(Short userState) {
		this.userState = userState;
	}

}
